### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/chargebot#1]
- [ ] send the chargeplan using notifications.
- [ ] send notification on start, stop and if chargeing isnt stopped/ started
- [ ] log and notify is we can charge full
- [x] create a callback for smart input Boolean so chargeplan is canceled and recreated.
- [ ] add proper logging
- [ ] cb for smart charge input so plan are canceled.
